---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Authorized host entry
      local_action:
        module: authorized_key
        user: root
        key: "{{ item }}"
        state: present
      with_file:
        - public_keys/bruce
      register: authorized_key
